name: Build and Push Spring Boot and MySQL Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK for building the Spring Boot application
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the Spring Boot application
      - name: Build the application
        run: ./mvn package

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image for Spring Boot
      - name: Build Docker image for Spring Boot
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .

      # Push the Spring Boot Docker image to Docker Hub
      - name: Push Docker image for Spring Boot
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

      # Build the Docker image for MySQL
      - name: Build Docker image for MySQL
        run: |
          echo "FROM mysql:8.0" > Dockerfile.mysql
          echo "ENV MYSQL_ROOT_PASSWORD=root" >> Dockerfile.mysql
          echo "ENV MYSQL_DATABASE=springbootdb" >> Dockerfile.mysql
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mysql-db:latest -f Dockerfile.mysql .

      # Push the MySQL Docker image to Docker Hub
      - name: Push Docker image for MySQL
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mysql-db:latest
