name: Build and Push Spring Boot Image

on:
  push:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      database:
        image: mysql:8
        env:
          MYSQL_DATABASE: ems
          MYSQL_USER: username
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - "3306:3306"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
 username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the application
        run: mvn clean package --file "./springboot-backend/pom.xml"

      - name: Run Tests
        run: mvn test --file "./springboot-backend/pom.xml"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./springboot-backend  # Set the context to the directory containing the Dockerfile
          file: ./springboot-backend/Dockerfile  # Specify the Dockerfile location
          push: true  # Push the image to Docker Hub after building
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-spring-bootapp:latest


      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if nc -z database 3306; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Application Integration Tests (Optional)
        run: mvn verify --file "./springboot-backend/pom.xml"
