name: Data Workflow

on:
  push:
    branches:
      - main

jobs:
  process-data:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run date.sh script
        run: |
          chmod +x ./date.sh
          ./date.sh
